jwt:
  secretKey: Q05VLVNQSUNZLUJPQVJELUFQUExJQ0FUSU9OLVNFQ1JFVF9LRVk= #TODO [CNU-SPICY-BOARD-APPLICATION-SECRET_KEY 를 base 64로 인코딩한 값]을 작성하세요.
  accessTokenExpirationDay: 100 # AccessToken의 만료기한은 100일로 설정합니다. (변경 가능)
